pipeline {
    agent any
    stages {
        stage('Ejemplo') {
            steps {
                script {
                    def unidadBase = env.WORKSPACE
                    echo "La unidad base es: ${unidadBase}"
                    // Tu lógica adicional aquí
                }
            }
        }
    }
}
