pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    git branch: 'rama/ActividadJenkins4', url: 'https://github.com/MarcosNavarro00/JavaIndra.git'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'Main.java'
                }
            }
        }

        stage('Run Java Program') {
            steps {
                script {
                    sh 'java InfraccionesSalariales'
                }
            }
        }
    }
}
